import sharp from 'sharp'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'

vi.mock('@/env', () => ({
	env: {
		LOG_LEVEL: 'silent',
		LOG_PRETTY: false,
		BETTER_AUTH_SECRET: 'test-secret',
		STORAGE_ENDPOINT: 'http://storage.test',
		STORAGE_REGION: 'us-east-1',
		STORAGE_BUCKET: 'test-bucket',
		STORAGE_ACCESS_KEY_ID: 'test-key',
		STORAGE_SECRET_ACCESS_KEY: 'test-secret',
		STORAGE_PUBLIC_URL: 'https://cdn.test',
		STORAGE_MAX_UPLOAD_MB: 8,
	},
}))

import type { StorageAdapter } from '../adapter'
import { _setStorageForTesting } from '../adapter'
import { mirrorRemoteImageToStorage } from '../mirror'

type FakeStorage = StorageAdapter & {
	uploads: Array<{ key: string; buffer: Buffer; contentType: string }>
}

function makeFakeStorage(overrides: Partial<StorageAdapter> = {}): FakeStorage {
	const uploads: FakeStorage['uploads'] = []
	const adapter: FakeStorage = {
		uploads,
		upload: vi.fn((key: string, buffer: Buffer, contentType: string) => {
			uploads.push({ key, buffer, contentType })
			return Promise.resolve()
		}),
		delete: vi.fn(() => Promise.resolve()),
		stream: vi.fn(),
		list: vi.fn(),
		ready: vi.fn(),
		getPublicUrl: (key: string) => `https://cdn.test/${key}`,
		...overrides,
	}
	return adapter
}

// 1x1 red PNG generated by sharp. Real image bytes so processImage's
// sharp pipeline runs end-to-end.
async function makeTinyPng(): Promise<Buffer> {
	return await sharp({
		create: { width: 1, height: 1, channels: 3, background: { r: 255, g: 0, b: 0 } },
	})
		.png()
		.toBuffer()
}

describe('mirrorRemoteImageToStorage', () => {
	beforeEach(() => {
		_setStorageForTesting(makeFakeStorage())
	})

	afterEach(() => {
		_setStorageForTesting(undefined)
		vi.unstubAllGlobals()
	})

	it('returns null when storage is not configured', async () => {
		_setStorageForTesting(undefined)
		// Force isStorageConfigured() false by stubbing env. The setup
		// above already sets all five vars, so we override here.
		const envMod = await import('@/env')
		const original = envMod.env.STORAGE_BUCKET
		;(envMod.env as { STORAGE_BUCKET: string | undefined }).STORAGE_BUCKET = undefined
		try {
			const result = await mirrorRemoteImageToStorage('https://1.1.1.1/img.png', 1)
			expect(result).toBeNull()
		} finally {
			;(envMod.env as { STORAGE_BUCKET: string | undefined }).STORAGE_BUCKET = original
		}
	})

	it('returns null when the URL is already a storage URL (no fetch)', async () => {
		const fetchMock = vi.fn()
		vi.stubGlobal('fetch', fetchMock)

		const result = await mirrorRemoteImageToStorage('https://cdn.test/items/1/abcdef0123.webp', 1)

		expect(result).toBeNull()
		expect(fetchMock).not.toHaveBeenCalled()
	})

	it('returns null for non-http(s) protocols', async () => {
		const fetchMock = vi.fn()
		vi.stubGlobal('fetch', fetchMock)

		expect(await mirrorRemoteImageToStorage('data:image/png;base64,xxx', 1)).toBeNull()
		expect(await mirrorRemoteImageToStorage('ftp://example.com/img.png', 1)).toBeNull()
		expect(fetchMock).not.toHaveBeenCalled()
	})

	it('returns null for malformed URLs', async () => {
		const fetchMock = vi.fn()
		vi.stubGlobal('fetch', fetchMock)
		expect(await mirrorRemoteImageToStorage('not a url', 1)).toBeNull()
		expect(fetchMock).not.toHaveBeenCalled()
	})

	it('downloads a remote PNG, processes it, uploads as webp, and returns the public URL', async () => {
		const png = await makeTinyPng()
		const storage = makeFakeStorage()
		_setStorageForTesting(storage)

		const pngBytes = new Uint8Array(png)
		vi.stubGlobal(
			'fetch',
			vi.fn(() =>
				Promise.resolve(
					new Response(pngBytes, {
						status: 200,
						headers: { 'content-type': 'image/png' },
					})
				)
			)
		)

		// IP literal sidesteps DNS resolution in safeFetch (assertSafeUrl
		// short-circuits on net.isIP).
		const result = await mirrorRemoteImageToStorage('https://1.1.1.1/cool.png', 42)

		expect(result).toMatch(/^https:\/\/cdn\.test\/items\/42\/[0-9A-Za-z]+\.webp$/)
		expect(storage.uploads).toHaveLength(1)
		expect(storage.uploads[0].contentType).toBe('image/webp')
		expect(storage.uploads[0].key).toMatch(/^items\/42\/[0-9A-Za-z]+\.webp$/)
		// Sharp's webp output starts with the RIFF...WEBP magic.
		expect(storage.uploads[0].buffer.toString('ascii', 0, 4)).toBe('RIFF')
		expect(storage.uploads[0].buffer.toString('ascii', 8, 12)).toBe('WEBP')
	})

	it('returns null when the remote responds with a non-image body', async () => {
		const storage = makeFakeStorage()
		_setStorageForTesting(storage)

		vi.stubGlobal(
			'fetch',
			vi.fn(() =>
				Promise.resolve(
					new Response('<html>not an image</html>', {
						status: 200,
						headers: { 'content-type': 'text/html' },
					})
				)
			)
		)

		const result = await mirrorRemoteImageToStorage('https://1.1.1.1/page.html', 1)

		expect(result).toBeNull()
		expect(storage.uploads).toHaveLength(0)
	})

	it('returns null when the network call rejects', async () => {
		const storage = makeFakeStorage()
		_setStorageForTesting(storage)

		vi.stubGlobal(
			'fetch',
			vi.fn(() => Promise.reject(new Error('econnreset')))
		)

		const result = await mirrorRemoteImageToStorage('https://1.1.1.1/x.png', 1)

		expect(result).toBeNull()
		expect(storage.uploads).toHaveLength(0)
	})

	it('returns null when content-length exceeds the upload cap', async () => {
		const storage = makeFakeStorage()
		_setStorageForTesting(storage)

		const oversize = 99 * 1024 * 1024
		vi.stubGlobal(
			'fetch',
			vi.fn(() =>
				Promise.resolve(
					new Response('xxx', {
						status: 200,
						headers: {
							'content-type': 'image/png',
							'content-length': String(oversize),
						},
					})
				)
			)
		)

		const result = await mirrorRemoteImageToStorage('https://1.1.1.1/big.png', 1)

		expect(result).toBeNull()
		expect(storage.uploads).toHaveLength(0)
	})

	it('returns null on non-2xx responses', async () => {
		const storage = makeFakeStorage()
		_setStorageForTesting(storage)

		vi.stubGlobal(
			'fetch',
			vi.fn(() => Promise.resolve(new Response('not found', { status: 404 })))
		)

		const result = await mirrorRemoteImageToStorage('https://1.1.1.1/missing.png', 1)

		expect(result).toBeNull()
		expect(storage.uploads).toHaveLength(0)
	})
})
