import {
	appSettings,
	customHolidayReminderLogs,
	customHolidays,
	dependentGuardianships,
	dependents,
	giftContributions,
	giftedItems,
	guardianships,
	itemComments,
	itemGroups,
	items,
	itemScrapeJobs,
	listAddons,
	listEditors,
	lists,
	recommendations,
	recommendationSubItemDismissals,
	todoItems,
	userRelationLabels,
	userRelationships,
	users,
} from '@/db/schema'

// Order used for inserts during import. Every referenced row must appear
// before any row that references it. users is written twice: once with
// partnerId=null, then again in a second pass to set partnerId.
export const BACKUP_TABLES = [
	{ name: 'users', table: users, idSequence: null },
	{ name: 'appSettings', table: appSettings, idSequence: null },
	{ name: 'userRelationships', table: userRelationships, idSequence: null },
	{ name: 'guardianships', table: guardianships, idSequence: null },
	{ name: 'dependents', table: dependents, idSequence: null },
	{ name: 'dependentGuardianships', table: dependentGuardianships, idSequence: null },
	{ name: 'userRelationLabels', table: userRelationLabels, idSequence: 'user_relation_labels_id_seq' },
	{ name: 'customHolidays', table: customHolidays, idSequence: null },
	{ name: 'customHolidayReminderLogs', table: customHolidayReminderLogs, idSequence: null },
	{ name: 'recommendations', table: recommendations, idSequence: null },
	{ name: 'recommendationSubItemDismissals', table: recommendationSubItemDismissals, idSequence: null },
	{ name: 'lists', table: lists, idSequence: 'lists_id_seq' },
	{ name: 'itemGroups', table: itemGroups, idSequence: 'item_groups_id_seq' },
	{ name: 'items', table: items, idSequence: 'items_id_seq' },
	{ name: 'itemScrapeJobs', table: itemScrapeJobs, idSequence: 'item_scrape_jobs_id_seq' },
	{ name: 'todoItems', table: todoItems, idSequence: 'todo_items_id_seq' },
	{ name: 'giftedItems', table: giftedItems, idSequence: 'gifted_items_id_seq' },
	{ name: 'giftContributions', table: giftContributions, idSequence: 'gift_contributions_id_seq' },
	{ name: 'itemComments', table: itemComments, idSequence: 'item_comments_id_seq' },
	{ name: 'listAddons', table: listAddons, idSequence: 'list_addons_id_seq' },
	{ name: 'listEditors', table: listEditors, idSequence: 'list_editors_id_seq' },
] as const

export type BackupTableName = (typeof BACKUP_TABLES)[number]['name']

// Reverse dependency order for DELETE during wipe. Children first.
// customHolidays (and its reminder logs, which cascade off it) are not
// listed: they're cleared separately, and only when the backup file
// carries the table (see restoreBackupTablesImpl).
export const BACKUP_TABLES_DELETE_ORDER = [
	listEditors,
	listAddons,
	itemComments,
	giftContributions,
	giftedItems,
	todoItems,
	itemScrapeJobs,
	items,
	itemGroups,
	lists,
	recommendationSubItemDismissals,
	recommendations,
	userRelationLabels,
	dependentGuardianships,
	dependents,
	guardianships,
	userRelationships,
	appSettings,
] as const

// Columns of a backed-up table deliberately left out of its row schema.
// The coverage test fails on any other column the row schema lacks.
export const BACKUP_OMITTED_COLUMNS: Partial<Record<BackupTableName, Record<string, string>>> = {
	users: {
		twoFactorEnabled: 'The TOTP secret lives in the never-exported twoFactor table; restoring the flag without it locks the user out.',
	},
}

// Tables (by physical name) deliberately not backed up. Everything here is
// either credentials, an ephemeral counter, history nobody acts on, or a
// cache the app rebuilds on demand. The coverage test fails on any table
// in `@/db/schema` that is neither backed up nor listed here.
const AUTH_STATE = 'better-auth credential / session state. Never exported; everyone re-authenticates after a restore.'
const REGENERATED = 'AI-derived cache, regenerated by the intelligence cron on its next run.'
export const BACKUP_EXCLUDED_TABLES: Record<string, string> = {
	session: AUTH_STATE,
	account: AUTH_STATE,
	verification: AUTH_STATE,
	rateLimit: AUTH_STATE,
	apikey: AUTH_STATE,
	twoFactor: AUTH_STATE,
	passkey: AUTH_STATE,
	rate_limit_buckets: 'Ephemeral fixed-window limiter counters.',
	cron_runs: 'Operator-facing cron run history. Nothing reads it to decide what to do.',
	product_lookups: 'Barcode lookup cache, refetched on miss.',
	item_scrapes: 'Scrape history and URL dedup cache (large raw responses). The scraped fields already live on items.',
	holiday_catalog: 'Reference data written only by seedHolidayCatalogIfEmpty; custom_holidays point at it by (country, key) text, not FK.',
	item_ai_analysis: REGENERATED,
	intelligence_verdicts: REGENERATED,
	recommendation_runs: `Run history plus per-scope input hashes. ${REGENERATED} Without them the next run regenerates every scope; dismissals still carry forward via recommendations.`,
	recommendation_run_steps: 'Per-analyzer prompt / response logs for operator debugging.',
}
