import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'

vi.mock('@/env', () => ({
	env: {
		LOG_LEVEL: 'silent',
		LOG_PRETTY: false,
		BETTER_AUTH_SECRET: 'test-secret',
	},
}))

let mockAiValid = false

vi.mock('@/lib/ai-config', () => ({
	resolveAiConfig: () =>
		Promise.resolve({
			isValid: mockAiValid,
			providerType: { source: 'env', value: 'openai' },
			baseUrl: { source: 'missing' },
			apiKey: { source: 'env', value: 'test-key' },
			model: { source: 'env', value: 'gpt-4o-mini' },
			maxOutputTokens: { source: 'default', value: 4096 },
		}),
}))

vi.mock('@/lib/ai-client', () => ({
	createAiModel: () => ({ __mock: true }),
}))

let generateObjectImpl: () => Promise<{ object: Record<string, unknown> }> = () =>
	Promise.resolve({
		object: {
			title: 'AI Result',
			description: 'Generated by mock',
			imageUrls: ['https://cdn.test/widget.jpg'],
		},
	})

vi.mock('ai', () => ({
	generateObject: (...args: Array<unknown>) => {
		void args
		return generateObjectImpl()
	},
}))

vi.mock('@/db', () => ({ db: {} }))

import type { AiEntry } from '@/lib/settings'

import type { ScrapeContext, ScrapeProvider } from '../../types'
import { createAiProvider } from '../ai'

const TEST_ENTRY: AiEntry = {
	type: 'ai',
	id: 'default',
	name: 'AI extraction',
	enabled: true,
	tier: 3,
}

function makeProvider(overrides: Partial<AiEntry> = {}): ScrapeProvider {
	return createAiProvider({ ...TEST_ENTRY, ...overrides })
}

function silentLogger(): ScrapeContext['logger'] {
	const noop = () => {}
	const fn = noop as unknown as ScrapeContext['logger']
	return new Proxy({} as object, { get: (_, p) => (p === 'child' ? () => fn : noop) }) as ScrapeContext['logger']
}

function makeCtx(url: string): ScrapeContext {
	return { url, signal: new AbortController().signal, logger: silentLogger(), perAttemptTimeoutMs: 5000 }
}

let fetchQueue: Array<{ status: number; body?: string }> = []

beforeEach(() => {
	mockAiValid = false
	fetchQueue = []
	generateObjectImpl = () =>
		Promise.resolve({
			object: { title: 'AI Result', description: 'Generated by mock', imageUrls: ['https://cdn.test/widget.jpg'] },
		})
	vi.stubGlobal('fetch', () => {
		const next = fetchQueue.shift()
		if (!next) throw new Error('fetch called more times than queued responses')
		return Promise.resolve(new Response(next.body ?? '<html></html>', { status: next.status, headers: { 'content-type': 'text/html' } }))
	})
})

afterEach(() => {
	vi.unstubAllGlobals()
})

describe('aiProvider: availability', () => {
	it('is unavailable when entry is disabled', async () => {
		mockAiValid = true
		await expect(Promise.resolve(makeProvider({ enabled: false }).isAvailable())).resolves.toBe(false)
	})

	it('is unavailable when AI config is invalid', async () => {
		mockAiValid = false
		await expect(Promise.resolve(makeProvider().isAvailable())).resolves.toBe(false)
	})

	it('is available when entry is enabled and AI config is valid', async () => {
		mockAiValid = true
		await expect(Promise.resolve(makeProvider().isAvailable())).resolves.toBe(true)
	})
})

describe('aiProvider: fetch', () => {
	beforeEach(() => {
		mockAiValid = true
	})

	it('fetches the URL and returns a StructuredResponse from the LLM', async () => {
		fetchQueue.push({ status: 200, body: '<html><body>page contents</body></html>' })
		const result = await makeProvider().fetch(makeCtx('https://target.test/x'))
		expect(result.kind).toBe('structured')
		if (result.kind !== 'structured') return
		expect(result.providerId).toBe('ai:default')
		expect(result.result.title).toBe('AI Result')
		expect(result.result.imageUrls).toEqual(['https://cdn.test/widget.jpg'])
		expect(result.result.finalUrl).toBe('https://target.test/x')
	})

	it('throws config_missing when AI is somehow not configured at fetch time', async () => {
		mockAiValid = false
		await expect(makeProvider().fetch(makeCtx('https://target.test/x'))).rejects.toMatchObject({ code: 'config_missing' })
	})

	it('classifies a 4xx fetch as http_4xx', async () => {
		fetchQueue.push({ status: 404 })
		await expect(makeProvider().fetch(makeCtx('https://target.test/x'))).rejects.toMatchObject({ code: 'http_4xx' })
	})

	it('classifies a 5xx fetch as http_5xx', async () => {
		fetchQueue.push({ status: 502 })
		await expect(makeProvider().fetch(makeCtx('https://target.test/x'))).rejects.toMatchObject({ code: 'http_5xx' })
	})

	it('throws bot_block when the fetched HTML is a CF wall', async () => {
		fetchQueue.push({ status: 200, body: '<html><body>cf-browser-verification</body></html>' })
		await expect(makeProvider().fetch(makeCtx('https://target.test/x'))).rejects.toMatchObject({ code: 'bot_block' })
	})

	it('classifies generateObject failures as invalid_response', async () => {
		fetchQueue.push({ status: 200, body: '<html><body>ok</body></html>' })
		generateObjectImpl = () => Promise.reject(new Error('LLM provider returned 5xx'))
		await expect(makeProvider().fetch(makeCtx('https://target.test/x'))).rejects.toMatchObject({ code: 'invalid_response' })
	})
})
