/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as coreRouteRouteImport } from './routes/(core)/route'
import { Route as coreIndexRouteImport } from './routes/(core)/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as coreTempRouteImport } from './routes/(core)/temp'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignOutRouteImport } from './routes/(auth)/sign-out'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as coreSettingsRouteRouteImport } from './routes/(core)/settings/route'
import { Route as coreAdminRouteRouteImport } from './routes/(core)/admin/route'
import { Route as coreSettingsIndexRouteImport } from './routes/(core)/settings/index'
import { Route as corePurchasesIndexRouteImport } from './routes/(core)/purchases.index'
import { Route as coreMeIndexRouteImport } from './routes/(core)/me.index'
import { Route as coreAdminIndexRouteImport } from './routes/(core)/admin/index'
import { Route as ApiSseListsRouteImport } from './routes/api/sse/lists'
import { Route as ApiListsPublicRouteImport } from './routes/api/lists/public'
import { Route as ApiFilesSplatRouteImport } from './routes/api/files/$'
import { Route as ApiCronBirthdayEmailsRouteImport } from './routes/api/cron/birthday-emails'
import { Route as ApiCronAutoArchiveRouteImport } from './routes/api/cron/auto-archive'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as coreSettingsSecurityRouteImport } from './routes/(core)/settings/security'
import { Route as coreSettingsPermissionsRouteImport } from './routes/(core)/settings/permissions'
import { Route as coreRecentItemsRouteImport } from './routes/(core)/recent.items'
import { Route as coreRecentCommentsRouteImport } from './routes/(core)/recent.comments'
import { Route as corePurchasesReceivedRouteImport } from './routes/(core)/purchases.received'
import { Route as coreListsListIdRouteImport } from './routes/(core)/lists/$listId'
import { Route as coreItemCloneRouteImport } from './routes/(core)/item.clone'
import { Route as coreAdminUsersRouteImport } from './routes/(core)/admin/users'
import { Route as coreAdminEmailRouteImport } from './routes/(core)/admin/email'
import { Route as coreAdminDebugRouteImport } from './routes/(core)/admin/debug'
import { Route as coreAdminDataRouteImport } from './routes/(core)/admin/data'
import { Route as coreAdminAiRouteImport } from './routes/(core)/admin/ai'
import { Route as ApiSseListListIdRouteImport } from './routes/api/sse/list.$listId'
import { Route as coreListsListIdOrganizeRouteImport } from './routes/(core)/lists_/$listId.organize'
import { Route as coreListsListIdEditRouteImport } from './routes/(core)/lists_/$listId.edit'
import { Route as coreListsListIdBulkRouteImport } from './routes/(core)/lists_/$listId.bulk'
import { Route as coreItemImportChar123UrlChar125RouteImport } from './routes/(core)/item.import.{-$url}'
import { Route as coreAdminUserIdRouteImport } from './routes/(core)/admin/user.$id'

const coreRouteRoute = coreRouteRouteImport.update({
  id: '/(core)',
  getParentRoute: () => rootRouteImport,
} as any)
const coreIndexRoute = coreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => coreRouteRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const coreTempRoute = coreTempRouteImport.update({
  id: '/temp',
  path: '/temp',
  getParentRoute: () => coreRouteRoute,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignOutRoute = authSignOutRouteImport.update({
  id: '/(auth)/sign-out',
  path: '/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const coreSettingsRouteRoute = coreSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => coreRouteRoute,
} as any)
const coreAdminRouteRoute = coreAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => coreRouteRoute,
} as any)
const coreSettingsIndexRoute = coreSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => coreSettingsRouteRoute,
} as any)
const corePurchasesIndexRoute = corePurchasesIndexRouteImport.update({
  id: '/purchases/',
  path: '/purchases/',
  getParentRoute: () => coreRouteRoute,
} as any)
const coreMeIndexRoute = coreMeIndexRouteImport.update({
  id: '/me/',
  path: '/me/',
  getParentRoute: () => coreRouteRoute,
} as any)
const coreAdminIndexRoute = coreAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => coreAdminRouteRoute,
} as any)
const ApiSseListsRoute = ApiSseListsRouteImport.update({
  id: '/api/sse/lists',
  path: '/api/sse/lists',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiListsPublicRoute = ApiListsPublicRouteImport.update({
  id: '/api/lists/public',
  path: '/api/lists/public',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesSplatRoute = ApiFilesSplatRouteImport.update({
  id: '/api/files/$',
  path: '/api/files/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronBirthdayEmailsRoute = ApiCronBirthdayEmailsRouteImport.update({
  id: '/api/cron/birthday-emails',
  path: '/api/cron/birthday-emails',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronAutoArchiveRoute = ApiCronAutoArchiveRouteImport.update({
  id: '/api/cron/auto-archive',
  path: '/api/cron/auto-archive',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const coreSettingsSecurityRoute = coreSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => coreSettingsRouteRoute,
} as any)
const coreSettingsPermissionsRoute = coreSettingsPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => coreSettingsRouteRoute,
} as any)
const coreRecentItemsRoute = coreRecentItemsRouteImport.update({
  id: '/recent/items',
  path: '/recent/items',
  getParentRoute: () => coreRouteRoute,
} as any)
const coreRecentCommentsRoute = coreRecentCommentsRouteImport.update({
  id: '/recent/comments',
  path: '/recent/comments',
  getParentRoute: () => coreRouteRoute,
} as any)
const corePurchasesReceivedRoute = corePurchasesReceivedRouteImport.update({
  id: '/purchases/received',
  path: '/purchases/received',
  getParentRoute: () => coreRouteRoute,
} as any)
const coreListsListIdRoute = coreListsListIdRouteImport.update({
  id: '/lists/$listId',
  path: '/lists/$listId',
  getParentRoute: () => coreRouteRoute,
} as any)
const coreItemCloneRoute = coreItemCloneRouteImport.update({
  id: '/item/clone',
  path: '/item/clone',
  getParentRoute: () => coreRouteRoute,
} as any)
const coreAdminUsersRoute = coreAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => coreAdminRouteRoute,
} as any)
const coreAdminEmailRoute = coreAdminEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => coreAdminRouteRoute,
} as any)
const coreAdminDebugRoute = coreAdminDebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => coreAdminRouteRoute,
} as any)
const coreAdminDataRoute = coreAdminDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => coreAdminRouteRoute,
} as any)
const coreAdminAiRoute = coreAdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => coreAdminRouteRoute,
} as any)
const ApiSseListListIdRoute = ApiSseListListIdRouteImport.update({
  id: '/api/sse/list/$listId',
  path: '/api/sse/list/$listId',
  getParentRoute: () => rootRouteImport,
} as any)
const coreListsListIdOrganizeRoute = coreListsListIdOrganizeRouteImport.update({
  id: '/lists_/$listId/organize',
  path: '/lists/$listId/organize',
  getParentRoute: () => coreRouteRoute,
} as any)
const coreListsListIdEditRoute = coreListsListIdEditRouteImport.update({
  id: '/lists_/$listId/edit',
  path: '/lists/$listId/edit',
  getParentRoute: () => coreRouteRoute,
} as any)
const coreListsListIdBulkRoute = coreListsListIdBulkRouteImport.update({
  id: '/lists_/$listId/bulk',
  path: '/lists/$listId/bulk',
  getParentRoute: () => coreRouteRoute,
} as any)
const coreItemImportChar123UrlChar125Route =
  coreItemImportChar123UrlChar125RouteImport.update({
    id: '/item/import/{-$url}',
    path: '/item/import/{-$url}',
    getParentRoute: () => coreRouteRoute,
  } as any)
const coreAdminUserIdRoute = coreAdminUserIdRouteImport.update({
  id: '/user/$id',
  path: '/user/$id',
  getParentRoute: () => coreAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof coreAdminRouteRouteWithChildren
  '/settings': typeof coreSettingsRouteRouteWithChildren
  '/sign-in': typeof authSignInRoute
  '/sign-out': typeof authSignOutRoute
  '/sign-up': typeof authSignUpRoute
  '/temp': typeof coreTempRoute
  '/api/health': typeof ApiHealthRoute
  '/': typeof coreIndexRoute
  '/admin/ai': typeof coreAdminAiRoute
  '/admin/data': typeof coreAdminDataRoute
  '/admin/debug': typeof coreAdminDebugRoute
  '/admin/email': typeof coreAdminEmailRoute
  '/admin/users': typeof coreAdminUsersRoute
  '/item/clone': typeof coreItemCloneRoute
  '/lists/$listId': typeof coreListsListIdRoute
  '/purchases/received': typeof corePurchasesReceivedRoute
  '/recent/comments': typeof coreRecentCommentsRoute
  '/recent/items': typeof coreRecentItemsRoute
  '/settings/permissions': typeof coreSettingsPermissionsRoute
  '/settings/security': typeof coreSettingsSecurityRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/auto-archive': typeof ApiCronAutoArchiveRoute
  '/api/cron/birthday-emails': typeof ApiCronBirthdayEmailsRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/lists/public': typeof ApiListsPublicRoute
  '/api/sse/lists': typeof ApiSseListsRoute
  '/admin/': typeof coreAdminIndexRoute
  '/me': typeof coreMeIndexRoute
  '/purchases': typeof corePurchasesIndexRoute
  '/settings/': typeof coreSettingsIndexRoute
  '/admin/user/$id': typeof coreAdminUserIdRoute
  '/item/import/{-$url}': typeof coreItemImportChar123UrlChar125Route
  '/lists/$listId/bulk': typeof coreListsListIdBulkRoute
  '/lists/$listId/edit': typeof coreListsListIdEditRoute
  '/lists/$listId/organize': typeof coreListsListIdOrganizeRoute
  '/api/sse/list/$listId': typeof ApiSseListListIdRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/sign-out': typeof authSignOutRoute
  '/sign-up': typeof authSignUpRoute
  '/temp': typeof coreTempRoute
  '/api/health': typeof ApiHealthRoute
  '/': typeof coreIndexRoute
  '/admin/ai': typeof coreAdminAiRoute
  '/admin/data': typeof coreAdminDataRoute
  '/admin/debug': typeof coreAdminDebugRoute
  '/admin/email': typeof coreAdminEmailRoute
  '/admin/users': typeof coreAdminUsersRoute
  '/item/clone': typeof coreItemCloneRoute
  '/lists/$listId': typeof coreListsListIdRoute
  '/purchases/received': typeof corePurchasesReceivedRoute
  '/recent/comments': typeof coreRecentCommentsRoute
  '/recent/items': typeof coreRecentItemsRoute
  '/settings/permissions': typeof coreSettingsPermissionsRoute
  '/settings/security': typeof coreSettingsSecurityRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/auto-archive': typeof ApiCronAutoArchiveRoute
  '/api/cron/birthday-emails': typeof ApiCronBirthdayEmailsRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/lists/public': typeof ApiListsPublicRoute
  '/api/sse/lists': typeof ApiSseListsRoute
  '/admin': typeof coreAdminIndexRoute
  '/me': typeof coreMeIndexRoute
  '/purchases': typeof corePurchasesIndexRoute
  '/settings': typeof coreSettingsIndexRoute
  '/admin/user/$id': typeof coreAdminUserIdRoute
  '/item/import/{-$url}': typeof coreItemImportChar123UrlChar125Route
  '/lists/$listId/bulk': typeof coreListsListIdBulkRoute
  '/lists/$listId/edit': typeof coreListsListIdEditRoute
  '/lists/$listId/organize': typeof coreListsListIdOrganizeRoute
  '/api/sse/list/$listId': typeof ApiSseListListIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(core)': typeof coreRouteRouteWithChildren
  '/(core)/admin': typeof coreAdminRouteRouteWithChildren
  '/(core)/settings': typeof coreSettingsRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-out': typeof authSignOutRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(core)/temp': typeof coreTempRoute
  '/api/health': typeof ApiHealthRoute
  '/(core)/': typeof coreIndexRoute
  '/(core)/admin/ai': typeof coreAdminAiRoute
  '/(core)/admin/data': typeof coreAdminDataRoute
  '/(core)/admin/debug': typeof coreAdminDebugRoute
  '/(core)/admin/email': typeof coreAdminEmailRoute
  '/(core)/admin/users': typeof coreAdminUsersRoute
  '/(core)/item/clone': typeof coreItemCloneRoute
  '/(core)/lists/$listId': typeof coreListsListIdRoute
  '/(core)/purchases/received': typeof corePurchasesReceivedRoute
  '/(core)/recent/comments': typeof coreRecentCommentsRoute
  '/(core)/recent/items': typeof coreRecentItemsRoute
  '/(core)/settings/permissions': typeof coreSettingsPermissionsRoute
  '/(core)/settings/security': typeof coreSettingsSecurityRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/auto-archive': typeof ApiCronAutoArchiveRoute
  '/api/cron/birthday-emails': typeof ApiCronBirthdayEmailsRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/lists/public': typeof ApiListsPublicRoute
  '/api/sse/lists': typeof ApiSseListsRoute
  '/(core)/admin/': typeof coreAdminIndexRoute
  '/(core)/me/': typeof coreMeIndexRoute
  '/(core)/purchases/': typeof corePurchasesIndexRoute
  '/(core)/settings/': typeof coreSettingsIndexRoute
  '/(core)/admin/user/$id': typeof coreAdminUserIdRoute
  '/(core)/item/import/{-$url}': typeof coreItemImportChar123UrlChar125Route
  '/(core)/lists_/$listId/bulk': typeof coreListsListIdBulkRoute
  '/(core)/lists_/$listId/edit': typeof coreListsListIdEditRoute
  '/(core)/lists_/$listId/organize': typeof coreListsListIdOrganizeRoute
  '/api/sse/list/$listId': typeof ApiSseListListIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/settings'
    | '/sign-in'
    | '/sign-out'
    | '/sign-up'
    | '/temp'
    | '/api/health'
    | '/'
    | '/admin/ai'
    | '/admin/data'
    | '/admin/debug'
    | '/admin/email'
    | '/admin/users'
    | '/item/clone'
    | '/lists/$listId'
    | '/purchases/received'
    | '/recent/comments'
    | '/recent/items'
    | '/settings/permissions'
    | '/settings/security'
    | '/api/auth/$'
    | '/api/cron/auto-archive'
    | '/api/cron/birthday-emails'
    | '/api/files/$'
    | '/api/lists/public'
    | '/api/sse/lists'
    | '/admin/'
    | '/me'
    | '/purchases'
    | '/settings/'
    | '/admin/user/$id'
    | '/item/import/{-$url}'
    | '/lists/$listId/bulk'
    | '/lists/$listId/edit'
    | '/lists/$listId/organize'
    | '/api/sse/list/$listId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-out'
    | '/sign-up'
    | '/temp'
    | '/api/health'
    | '/'
    | '/admin/ai'
    | '/admin/data'
    | '/admin/debug'
    | '/admin/email'
    | '/admin/users'
    | '/item/clone'
    | '/lists/$listId'
    | '/purchases/received'
    | '/recent/comments'
    | '/recent/items'
    | '/settings/permissions'
    | '/settings/security'
    | '/api/auth/$'
    | '/api/cron/auto-archive'
    | '/api/cron/birthday-emails'
    | '/api/files/$'
    | '/api/lists/public'
    | '/api/sse/lists'
    | '/admin'
    | '/me'
    | '/purchases'
    | '/settings'
    | '/admin/user/$id'
    | '/item/import/{-$url}'
    | '/lists/$listId/bulk'
    | '/lists/$listId/edit'
    | '/lists/$listId/organize'
    | '/api/sse/list/$listId'
  id:
    | '__root__'
    | '/(core)'
    | '/(core)/admin'
    | '/(core)/settings'
    | '/(auth)/sign-in'
    | '/(auth)/sign-out'
    | '/(auth)/sign-up'
    | '/(core)/temp'
    | '/api/health'
    | '/(core)/'
    | '/(core)/admin/ai'
    | '/(core)/admin/data'
    | '/(core)/admin/debug'
    | '/(core)/admin/email'
    | '/(core)/admin/users'
    | '/(core)/item/clone'
    | '/(core)/lists/$listId'
    | '/(core)/purchases/received'
    | '/(core)/recent/comments'
    | '/(core)/recent/items'
    | '/(core)/settings/permissions'
    | '/(core)/settings/security'
    | '/api/auth/$'
    | '/api/cron/auto-archive'
    | '/api/cron/birthday-emails'
    | '/api/files/$'
    | '/api/lists/public'
    | '/api/sse/lists'
    | '/(core)/admin/'
    | '/(core)/me/'
    | '/(core)/purchases/'
    | '/(core)/settings/'
    | '/(core)/admin/user/$id'
    | '/(core)/item/import/{-$url}'
    | '/(core)/lists_/$listId/bulk'
    | '/(core)/lists_/$listId/edit'
    | '/(core)/lists_/$listId/organize'
    | '/api/sse/list/$listId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  coreRouteRoute: typeof coreRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  authSignOutRoute: typeof authSignOutRoute
  authSignUpRoute: typeof authSignUpRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronAutoArchiveRoute: typeof ApiCronAutoArchiveRoute
  ApiCronBirthdayEmailsRoute: typeof ApiCronBirthdayEmailsRoute
  ApiFilesSplatRoute: typeof ApiFilesSplatRoute
  ApiListsPublicRoute: typeof ApiListsPublicRoute
  ApiSseListsRoute: typeof ApiSseListsRoute
  ApiSseListListIdRoute: typeof ApiSseListListIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(core)': {
      id: '/(core)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof coreRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(core)/': {
      id: '/(core)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof coreIndexRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(core)/temp': {
      id: '/(core)/temp'
      path: '/temp'
      fullPath: '/temp'
      preLoaderRoute: typeof coreTempRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-out': {
      id: '/(auth)/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof authSignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(core)/settings': {
      id: '/(core)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof coreSettingsRouteRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/(core)/admin': {
      id: '/(core)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof coreAdminRouteRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/(core)/settings/': {
      id: '/(core)/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof coreSettingsIndexRouteImport
      parentRoute: typeof coreSettingsRouteRoute
    }
    '/(core)/purchases/': {
      id: '/(core)/purchases/'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof corePurchasesIndexRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/(core)/me/': {
      id: '/(core)/me/'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof coreMeIndexRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/(core)/admin/': {
      id: '/(core)/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof coreAdminIndexRouteImport
      parentRoute: typeof coreAdminRouteRoute
    }
    '/api/sse/lists': {
      id: '/api/sse/lists'
      path: '/api/sse/lists'
      fullPath: '/api/sse/lists'
      preLoaderRoute: typeof ApiSseListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lists/public': {
      id: '/api/lists/public'
      path: '/api/lists/public'
      fullPath: '/api/lists/public'
      preLoaderRoute: typeof ApiListsPublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$': {
      id: '/api/files/$'
      path: '/api/files/$'
      fullPath: '/api/files/$'
      preLoaderRoute: typeof ApiFilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/birthday-emails': {
      id: '/api/cron/birthday-emails'
      path: '/api/cron/birthday-emails'
      fullPath: '/api/cron/birthday-emails'
      preLoaderRoute: typeof ApiCronBirthdayEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/auto-archive': {
      id: '/api/cron/auto-archive'
      path: '/api/cron/auto-archive'
      fullPath: '/api/cron/auto-archive'
      preLoaderRoute: typeof ApiCronAutoArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(core)/settings/security': {
      id: '/(core)/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof coreSettingsSecurityRouteImport
      parentRoute: typeof coreSettingsRouteRoute
    }
    '/(core)/settings/permissions': {
      id: '/(core)/settings/permissions'
      path: '/permissions'
      fullPath: '/settings/permissions'
      preLoaderRoute: typeof coreSettingsPermissionsRouteImport
      parentRoute: typeof coreSettingsRouteRoute
    }
    '/(core)/recent/items': {
      id: '/(core)/recent/items'
      path: '/recent/items'
      fullPath: '/recent/items'
      preLoaderRoute: typeof coreRecentItemsRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/(core)/recent/comments': {
      id: '/(core)/recent/comments'
      path: '/recent/comments'
      fullPath: '/recent/comments'
      preLoaderRoute: typeof coreRecentCommentsRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/(core)/purchases/received': {
      id: '/(core)/purchases/received'
      path: '/purchases/received'
      fullPath: '/purchases/received'
      preLoaderRoute: typeof corePurchasesReceivedRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/(core)/lists/$listId': {
      id: '/(core)/lists/$listId'
      path: '/lists/$listId'
      fullPath: '/lists/$listId'
      preLoaderRoute: typeof coreListsListIdRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/(core)/item/clone': {
      id: '/(core)/item/clone'
      path: '/item/clone'
      fullPath: '/item/clone'
      preLoaderRoute: typeof coreItemCloneRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/(core)/admin/users': {
      id: '/(core)/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof coreAdminUsersRouteImport
      parentRoute: typeof coreAdminRouteRoute
    }
    '/(core)/admin/email': {
      id: '/(core)/admin/email'
      path: '/email'
      fullPath: '/admin/email'
      preLoaderRoute: typeof coreAdminEmailRouteImport
      parentRoute: typeof coreAdminRouteRoute
    }
    '/(core)/admin/debug': {
      id: '/(core)/admin/debug'
      path: '/debug'
      fullPath: '/admin/debug'
      preLoaderRoute: typeof coreAdminDebugRouteImport
      parentRoute: typeof coreAdminRouteRoute
    }
    '/(core)/admin/data': {
      id: '/(core)/admin/data'
      path: '/data'
      fullPath: '/admin/data'
      preLoaderRoute: typeof coreAdminDataRouteImport
      parentRoute: typeof coreAdminRouteRoute
    }
    '/(core)/admin/ai': {
      id: '/(core)/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof coreAdminAiRouteImport
      parentRoute: typeof coreAdminRouteRoute
    }
    '/api/sse/list/$listId': {
      id: '/api/sse/list/$listId'
      path: '/api/sse/list/$listId'
      fullPath: '/api/sse/list/$listId'
      preLoaderRoute: typeof ApiSseListListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(core)/lists_/$listId/organize': {
      id: '/(core)/lists_/$listId/organize'
      path: '/lists/$listId/organize'
      fullPath: '/lists/$listId/organize'
      preLoaderRoute: typeof coreListsListIdOrganizeRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/(core)/lists_/$listId/edit': {
      id: '/(core)/lists_/$listId/edit'
      path: '/lists/$listId/edit'
      fullPath: '/lists/$listId/edit'
      preLoaderRoute: typeof coreListsListIdEditRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/(core)/lists_/$listId/bulk': {
      id: '/(core)/lists_/$listId/bulk'
      path: '/lists/$listId/bulk'
      fullPath: '/lists/$listId/bulk'
      preLoaderRoute: typeof coreListsListIdBulkRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/(core)/item/import/{-$url}': {
      id: '/(core)/item/import/{-$url}'
      path: '/item/import/{-$url}'
      fullPath: '/item/import/{-$url}'
      preLoaderRoute: typeof coreItemImportChar123UrlChar125RouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/(core)/admin/user/$id': {
      id: '/(core)/admin/user/$id'
      path: '/user/$id'
      fullPath: '/admin/user/$id'
      preLoaderRoute: typeof coreAdminUserIdRouteImport
      parentRoute: typeof coreAdminRouteRoute
    }
  }
}

interface coreAdminRouteRouteChildren {
  coreAdminAiRoute: typeof coreAdminAiRoute
  coreAdminDataRoute: typeof coreAdminDataRoute
  coreAdminDebugRoute: typeof coreAdminDebugRoute
  coreAdminEmailRoute: typeof coreAdminEmailRoute
  coreAdminUsersRoute: typeof coreAdminUsersRoute
  coreAdminIndexRoute: typeof coreAdminIndexRoute
  coreAdminUserIdRoute: typeof coreAdminUserIdRoute
}

const coreAdminRouteRouteChildren: coreAdminRouteRouteChildren = {
  coreAdminAiRoute: coreAdminAiRoute,
  coreAdminDataRoute: coreAdminDataRoute,
  coreAdminDebugRoute: coreAdminDebugRoute,
  coreAdminEmailRoute: coreAdminEmailRoute,
  coreAdminUsersRoute: coreAdminUsersRoute,
  coreAdminIndexRoute: coreAdminIndexRoute,
  coreAdminUserIdRoute: coreAdminUserIdRoute,
}

const coreAdminRouteRouteWithChildren = coreAdminRouteRoute._addFileChildren(
  coreAdminRouteRouteChildren,
)

interface coreSettingsRouteRouteChildren {
  coreSettingsPermissionsRoute: typeof coreSettingsPermissionsRoute
  coreSettingsSecurityRoute: typeof coreSettingsSecurityRoute
  coreSettingsIndexRoute: typeof coreSettingsIndexRoute
}

const coreSettingsRouteRouteChildren: coreSettingsRouteRouteChildren = {
  coreSettingsPermissionsRoute: coreSettingsPermissionsRoute,
  coreSettingsSecurityRoute: coreSettingsSecurityRoute,
  coreSettingsIndexRoute: coreSettingsIndexRoute,
}

const coreSettingsRouteRouteWithChildren =
  coreSettingsRouteRoute._addFileChildren(coreSettingsRouteRouteChildren)

interface coreRouteRouteChildren {
  coreAdminRouteRoute: typeof coreAdminRouteRouteWithChildren
  coreSettingsRouteRoute: typeof coreSettingsRouteRouteWithChildren
  coreTempRoute: typeof coreTempRoute
  coreIndexRoute: typeof coreIndexRoute
  coreItemCloneRoute: typeof coreItemCloneRoute
  coreListsListIdRoute: typeof coreListsListIdRoute
  corePurchasesReceivedRoute: typeof corePurchasesReceivedRoute
  coreRecentCommentsRoute: typeof coreRecentCommentsRoute
  coreRecentItemsRoute: typeof coreRecentItemsRoute
  coreMeIndexRoute: typeof coreMeIndexRoute
  corePurchasesIndexRoute: typeof corePurchasesIndexRoute
  coreItemImportChar123UrlChar125Route: typeof coreItemImportChar123UrlChar125Route
  coreListsListIdBulkRoute: typeof coreListsListIdBulkRoute
  coreListsListIdEditRoute: typeof coreListsListIdEditRoute
  coreListsListIdOrganizeRoute: typeof coreListsListIdOrganizeRoute
}

const coreRouteRouteChildren: coreRouteRouteChildren = {
  coreAdminRouteRoute: coreAdminRouteRouteWithChildren,
  coreSettingsRouteRoute: coreSettingsRouteRouteWithChildren,
  coreTempRoute: coreTempRoute,
  coreIndexRoute: coreIndexRoute,
  coreItemCloneRoute: coreItemCloneRoute,
  coreListsListIdRoute: coreListsListIdRoute,
  corePurchasesReceivedRoute: corePurchasesReceivedRoute,
  coreRecentCommentsRoute: coreRecentCommentsRoute,
  coreRecentItemsRoute: coreRecentItemsRoute,
  coreMeIndexRoute: coreMeIndexRoute,
  corePurchasesIndexRoute: corePurchasesIndexRoute,
  coreItemImportChar123UrlChar125Route: coreItemImportChar123UrlChar125Route,
  coreListsListIdBulkRoute: coreListsListIdBulkRoute,
  coreListsListIdEditRoute: coreListsListIdEditRoute,
  coreListsListIdOrganizeRoute: coreListsListIdOrganizeRoute,
}

const coreRouteRouteWithChildren = coreRouteRoute._addFileChildren(
  coreRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  coreRouteRoute: coreRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
  authSignOutRoute: authSignOutRoute,
  authSignUpRoute: authSignUpRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronAutoArchiveRoute: ApiCronAutoArchiveRoute,
  ApiCronBirthdayEmailsRoute: ApiCronBirthdayEmailsRoute,
  ApiFilesSplatRoute: ApiFilesSplatRoute,
  ApiListsPublicRoute: ApiListsPublicRoute,
  ApiSseListsRoute: ApiSseListsRoute,
  ApiSseListListIdRoute: ApiSseListListIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
