/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as MeIndexRouteImport } from './routes/me.index'
import { Route as ListsIndexRouteImport } from './routes/lists/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TestStylesRouteImport } from './routes/test.styles'
import { Route as SettingsSecurityRouteImport } from './routes/settings/security'
import { Route as SettingsReceivedRouteImport } from './routes/settings/received'
import { Route as SettingsPurchasesRouteImport } from './routes/settings/purchases'
import { Route as SettingsPermissionsRouteImport } from './routes/settings/permissions'
import { Route as SettingsConnectionsRouteImport } from './routes/settings/connections'
import { Route as RecentItemsRouteImport } from './routes/recent.items'
import { Route as RecentCommentsRouteImport } from './routes/recent.comments'
import { Route as MeNewRouteImport } from './routes/me.new'
import { Route as ListsListIdRouteImport } from './routes/lists/$listId'
import { Route as ItemCloneRouteImport } from './routes/item.clone'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignOutRouteImport } from './routes/(auth)/sign-out'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as ListsListIdEditRouteImport } from './routes/lists_/$listId.edit'
import { Route as ListsListIdBulkRouteImport } from './routes/lists_/$listId.bulk'
import { Route as ItemImportChar123UrlChar125RouteImport } from './routes/item.import.{-$url}'
import { Route as ApiListsPublicRouteImport } from './routes/api/lists/public'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const MeIndexRoute = MeIndexRouteImport.update({
  id: '/me/',
  path: '/me/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsIndexRoute = ListsIndexRouteImport.update({
  id: '/lists/',
  path: '/lists/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestStylesRoute = TestStylesRouteImport.update({
  id: '/test/styles',
  path: '/test/styles',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsReceivedRoute = SettingsReceivedRouteImport.update({
  id: '/received',
  path: '/received',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsPurchasesRoute = SettingsPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsPermissionsRoute = SettingsPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsConnectionsRoute = SettingsConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const RecentItemsRoute = RecentItemsRouteImport.update({
  id: '/recent/items',
  path: '/recent/items',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentCommentsRoute = RecentCommentsRouteImport.update({
  id: '/recent/comments',
  path: '/recent/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const MeNewRoute = MeNewRouteImport.update({
  id: '/me/new',
  path: '/me/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsListIdRoute = ListsListIdRouteImport.update({
  id: '/lists/$listId',
  path: '/lists/$listId',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemCloneRoute = ItemCloneRouteImport.update({
  id: '/item/clone',
  path: '/item/clone',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignOutRoute = authSignOutRouteImport.update({
  id: '/(auth)/sign-out',
  path: '/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsListIdEditRoute = ListsListIdEditRouteImport.update({
  id: '/lists_/$listId/edit',
  path: '/lists/$listId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsListIdBulkRoute = ListsListIdBulkRouteImport.update({
  id: '/lists_/$listId/bulk',
  path: '/lists/$listId/bulk',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemImportChar123UrlChar125Route =
  ItemImportChar123UrlChar125RouteImport.update({
    id: '/item/import/{-$url}',
    path: '/item/import/{-$url}',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiListsPublicRoute = ApiListsPublicRouteImport.update({
  id: '/api/lists/public',
  path: '/api/lists/public',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/purchases': typeof PurchasesRoute
  '/sign-in': typeof authSignInRoute
  '/sign-out': typeof authSignOutRoute
  '/sign-up': typeof authSignUpRoute
  '/item/clone': typeof ItemCloneRoute
  '/lists/$listId': typeof ListsListIdRoute
  '/me/new': typeof MeNewRoute
  '/recent/comments': typeof RecentCommentsRoute
  '/recent/items': typeof RecentItemsRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/permissions': typeof SettingsPermissionsRoute
  '/settings/purchases': typeof SettingsPurchasesRoute
  '/settings/received': typeof SettingsReceivedRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/test/styles': typeof TestStylesRoute
  '/admin': typeof AdminIndexRoute
  '/lists': typeof ListsIndexRoute
  '/me': typeof MeIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/lists/public': typeof ApiListsPublicRoute
  '/item/import/{-$url}': typeof ItemImportChar123UrlChar125Route
  '/lists/$listId/bulk': typeof ListsListIdBulkRoute
  '/lists/$listId/edit': typeof ListsListIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/purchases': typeof PurchasesRoute
  '/sign-in': typeof authSignInRoute
  '/sign-out': typeof authSignOutRoute
  '/sign-up': typeof authSignUpRoute
  '/item/clone': typeof ItemCloneRoute
  '/lists/$listId': typeof ListsListIdRoute
  '/me/new': typeof MeNewRoute
  '/recent/comments': typeof RecentCommentsRoute
  '/recent/items': typeof RecentItemsRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/permissions': typeof SettingsPermissionsRoute
  '/settings/purchases': typeof SettingsPurchasesRoute
  '/settings/received': typeof SettingsReceivedRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/test/styles': typeof TestStylesRoute
  '/admin': typeof AdminIndexRoute
  '/lists': typeof ListsIndexRoute
  '/me': typeof MeIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/lists/public': typeof ApiListsPublicRoute
  '/item/import/{-$url}': typeof ItemImportChar123UrlChar125Route
  '/lists/$listId/bulk': typeof ListsListIdBulkRoute
  '/lists/$listId/edit': typeof ListsListIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/purchases': typeof PurchasesRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-out': typeof authSignOutRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/item/clone': typeof ItemCloneRoute
  '/lists/$listId': typeof ListsListIdRoute
  '/me/new': typeof MeNewRoute
  '/recent/comments': typeof RecentCommentsRoute
  '/recent/items': typeof RecentItemsRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/permissions': typeof SettingsPermissionsRoute
  '/settings/purchases': typeof SettingsPurchasesRoute
  '/settings/received': typeof SettingsReceivedRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/test/styles': typeof TestStylesRoute
  '/admin/': typeof AdminIndexRoute
  '/lists/': typeof ListsIndexRoute
  '/me/': typeof MeIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/lists/public': typeof ApiListsPublicRoute
  '/item/import/{-$url}': typeof ItemImportChar123UrlChar125Route
  '/lists_/$listId/bulk': typeof ListsListIdBulkRoute
  '/lists_/$listId/edit': typeof ListsListIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/purchases'
    | '/sign-in'
    | '/sign-out'
    | '/sign-up'
    | '/item/clone'
    | '/lists/$listId'
    | '/me/new'
    | '/recent/comments'
    | '/recent/items'
    | '/settings/connections'
    | '/settings/permissions'
    | '/settings/purchases'
    | '/settings/received'
    | '/settings/security'
    | '/test/styles'
    | '/admin'
    | '/lists'
    | '/me'
    | '/settings/'
    | '/api/auth/$'
    | '/api/lists/public'
    | '/item/import/{-$url}'
    | '/lists/$listId/bulk'
    | '/lists/$listId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/purchases'
    | '/sign-in'
    | '/sign-out'
    | '/sign-up'
    | '/item/clone'
    | '/lists/$listId'
    | '/me/new'
    | '/recent/comments'
    | '/recent/items'
    | '/settings/connections'
    | '/settings/permissions'
    | '/settings/purchases'
    | '/settings/received'
    | '/settings/security'
    | '/test/styles'
    | '/admin'
    | '/lists'
    | '/me'
    | '/settings'
    | '/api/auth/$'
    | '/api/lists/public'
    | '/item/import/{-$url}'
    | '/lists/$listId/bulk'
    | '/lists/$listId/edit'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/purchases'
    | '/(auth)/sign-in'
    | '/(auth)/sign-out'
    | '/(auth)/sign-up'
    | '/item/clone'
    | '/lists/$listId'
    | '/me/new'
    | '/recent/comments'
    | '/recent/items'
    | '/settings/connections'
    | '/settings/permissions'
    | '/settings/purchases'
    | '/settings/received'
    | '/settings/security'
    | '/test/styles'
    | '/admin/'
    | '/lists/'
    | '/me/'
    | '/settings/'
    | '/api/auth/$'
    | '/api/lists/public'
    | '/item/import/{-$url}'
    | '/lists_/$listId/bulk'
    | '/lists_/$listId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  PurchasesRoute: typeof PurchasesRoute
  authSignInRoute: typeof authSignInRoute
  authSignOutRoute: typeof authSignOutRoute
  authSignUpRoute: typeof authSignUpRoute
  ItemCloneRoute: typeof ItemCloneRoute
  ListsListIdRoute: typeof ListsListIdRoute
  MeNewRoute: typeof MeNewRoute
  RecentCommentsRoute: typeof RecentCommentsRoute
  RecentItemsRoute: typeof RecentItemsRoute
  TestStylesRoute: typeof TestStylesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ListsIndexRoute: typeof ListsIndexRoute
  MeIndexRoute: typeof MeIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiListsPublicRoute: typeof ApiListsPublicRoute
  ItemImportChar123UrlChar125Route: typeof ItemImportChar123UrlChar125Route
  ListsListIdBulkRoute: typeof ListsListIdBulkRoute
  ListsListIdEditRoute: typeof ListsListIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/me/': {
      id: '/me/'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/': {
      id: '/lists/'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof ListsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/styles': {
      id: '/test/styles'
      path: '/test/styles'
      fullPath: '/test/styles'
      preLoaderRoute: typeof TestStylesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/received': {
      id: '/settings/received'
      path: '/received'
      fullPath: '/settings/received'
      preLoaderRoute: typeof SettingsReceivedRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/purchases': {
      id: '/settings/purchases'
      path: '/purchases'
      fullPath: '/settings/purchases'
      preLoaderRoute: typeof SettingsPurchasesRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/permissions': {
      id: '/settings/permissions'
      path: '/permissions'
      fullPath: '/settings/permissions'
      preLoaderRoute: typeof SettingsPermissionsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/connections': {
      id: '/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof SettingsConnectionsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/recent/items': {
      id: '/recent/items'
      path: '/recent/items'
      fullPath: '/recent/items'
      preLoaderRoute: typeof RecentItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent/comments': {
      id: '/recent/comments'
      path: '/recent/comments'
      fullPath: '/recent/comments'
      preLoaderRoute: typeof RecentCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/new': {
      id: '/me/new'
      path: '/me/new'
      fullPath: '/me/new'
      preLoaderRoute: typeof MeNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/$listId': {
      id: '/lists/$listId'
      path: '/lists/$listId'
      fullPath: '/lists/$listId'
      preLoaderRoute: typeof ListsListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item/clone': {
      id: '/item/clone'
      path: '/item/clone'
      fullPath: '/item/clone'
      preLoaderRoute: typeof ItemCloneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-out': {
      id: '/(auth)/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof authSignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists_/$listId/edit': {
      id: '/lists_/$listId/edit'
      path: '/lists/$listId/edit'
      fullPath: '/lists/$listId/edit'
      preLoaderRoute: typeof ListsListIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists_/$listId/bulk': {
      id: '/lists_/$listId/bulk'
      path: '/lists/$listId/bulk'
      fullPath: '/lists/$listId/bulk'
      preLoaderRoute: typeof ListsListIdBulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item/import/{-$url}': {
      id: '/item/import/{-$url}'
      path: '/item/import/{-$url}'
      fullPath: '/item/import/{-$url}'
      preLoaderRoute: typeof ItemImportChar123UrlChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lists/public': {
      id: '/api/lists/public'
      path: '/api/lists/public'
      fullPath: '/api/lists/public'
      preLoaderRoute: typeof ApiListsPublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteRouteChildren {
  SettingsConnectionsRoute: typeof SettingsConnectionsRoute
  SettingsPermissionsRoute: typeof SettingsPermissionsRoute
  SettingsPurchasesRoute: typeof SettingsPurchasesRoute
  SettingsReceivedRoute: typeof SettingsReceivedRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsConnectionsRoute: SettingsConnectionsRoute,
  SettingsPermissionsRoute: SettingsPermissionsRoute,
  SettingsPurchasesRoute: SettingsPurchasesRoute,
  SettingsReceivedRoute: SettingsReceivedRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  PurchasesRoute: PurchasesRoute,
  authSignInRoute: authSignInRoute,
  authSignOutRoute: authSignOutRoute,
  authSignUpRoute: authSignUpRoute,
  ItemCloneRoute: ItemCloneRoute,
  ListsListIdRoute: ListsListIdRoute,
  MeNewRoute: MeNewRoute,
  RecentCommentsRoute: RecentCommentsRoute,
  RecentItemsRoute: RecentItemsRoute,
  TestStylesRoute: TestStylesRoute,
  AdminIndexRoute: AdminIndexRoute,
  ListsIndexRoute: ListsIndexRoute,
  MeIndexRoute: MeIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiListsPublicRoute: ApiListsPublicRoute,
  ItemImportChar123UrlChar125Route: ItemImportChar123UrlChar125Route,
  ListsListIdBulkRoute: ListsListIdBulkRoute,
  ListsListIdEditRoute: ListsListIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
