/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as coreRouteRouteImport } from './routes/(core)/route'
import { Route as coreIndexRouteImport } from './routes/(core)/index'
import { Route as ApiVersionRouteImport } from './routes/api/version'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as coreImportRouteImport } from './routes/(core)/import'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignOutRouteImport } from './routes/(auth)/sign-out'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as coreTempRouteRouteImport } from './routes/(core)/temp/route'
import { Route as coreSettingsRouteRouteImport } from './routes/(core)/settings/route'
import { Route as coreAdminRouteRouteImport } from './routes/(core)/admin/route'
import { Route as coreTempIndexRouteImport } from './routes/(core)/temp/index'
import { Route as coreSettingsIndexRouteImport } from './routes/(core)/settings/index'
import { Route as corePurchasesIndexRouteImport } from './routes/(core)/purchases.index'
import { Route as coreMeIndexRouteImport } from './routes/(core)/me.index'
import { Route as coreAdminIndexRouteImport } from './routes/(core)/admin/index'
import { Route as ApiSseListsRouteImport } from './routes/api/sse/lists'
import { Route as ApiScrapeStreamRouteImport } from './routes/api/scrape/stream'
import { Route as ApiMobileSplatRouteImport } from './routes/api/mobile/$'
import { Route as ApiListsPublicRouteImport } from './routes/api/lists/public'
import { Route as ApiFilesSplatRouteImport } from './routes/api/files/$'
import { Route as ApiCronCleanupVerificationRouteImport } from './routes/api/cron/cleanup-verification'
import { Route as ApiCronBirthdayEmailsRouteImport } from './routes/api/cron/birthday-emails'
import { Route as ApiCronAutoArchiveRouteImport } from './routes/api/cron/auto-archive'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as coreTempWidgetsRouteImport } from './routes/(core)/temp/widgets'
import { Route as coreSettingsSecurityRouteImport } from './routes/(core)/settings/security'
import { Route as coreSettingsPermissionsRouteImport } from './routes/(core)/settings/permissions'
import { Route as coreSettingsDevicesRouteImport } from './routes/(core)/settings/devices'
import { Route as coreRecentItemsRouteImport } from './routes/(core)/recent.items'
import { Route as coreRecentCommentsRouteImport } from './routes/(core)/recent.comments'
import { Route as corePurchasesReceivedRouteImport } from './routes/(core)/purchases.received'
import { Route as coreOauthConsentRouteImport } from './routes/(core)/oauth.consent'
import { Route as coreListsListIdRouteImport } from './routes/(core)/lists/$listId'
import { Route as coreItemCloneRouteImport } from './routes/(core)/item.clone'
import { Route as coreAdminUsersRouteImport } from './routes/(core)/admin/users'
import { Route as coreAdminStorageRouteImport } from './routes/(core)/admin/storage'
import { Route as coreAdminScrapingRouteImport } from './routes/(core)/admin/scraping'
import { Route as coreAdminScrapesRouteImport } from './routes/(core)/admin/scrapes'
import { Route as coreAdminOidcRouteImport } from './routes/(core)/admin/oidc'
import { Route as coreAdminEmailRouteImport } from './routes/(core)/admin/email'
import { Route as coreAdminDebugRouteImport } from './routes/(core)/admin/debug'
import { Route as coreAdminDataRouteImport } from './routes/(core)/admin/data'
import { Route as coreAdminAiRouteImport } from './routes/(core)/admin/ai'
import { Route as authSignInTwoFactorRouteImport } from './routes/(auth)/sign-in.two-factor'
import { Route as ApiSseListListIdRouteImport } from './routes/api/sse/list.$listId'
import { Route as coreListsListIdOrganizeRouteImport } from './routes/(core)/lists_/$listId.organize'
import { Route as coreListsListIdEditRouteImport } from './routes/(core)/lists_/$listId.edit'
import { Route as coreListsListIdBulkRouteImport } from './routes/(core)/lists_/$listId.bulk'
import { Route as coreAdminUserIdRouteImport } from './routes/(core)/admin/user.$id'

const coreRouteRoute = coreRouteRouteImport.update({
  id: '/(core)',
  getParentRoute: () => rootRouteImport,
} as any)
const coreIndexRoute = coreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => coreRouteRoute,
} as any)
const ApiVersionRoute = ApiVersionRouteImport.update({
  id: '/api/version',
  path: '/api/version',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const coreImportRoute = coreImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => coreRouteRoute,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignOutRoute = authSignOutRouteImport.update({
  id: '/(auth)/sign-out',
  path: '/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const coreTempRouteRoute = coreTempRouteRouteImport.update({
  id: '/temp',
  path: '/temp',
  getParentRoute: () => coreRouteRoute,
} as any)
const coreSettingsRouteRoute = coreSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => coreRouteRoute,
} as any)
const coreAdminRouteRoute = coreAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => coreRouteRoute,
} as any)
const coreTempIndexRoute = coreTempIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => coreTempRouteRoute,
} as any)
const coreSettingsIndexRoute = coreSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => coreSettingsRouteRoute,
} as any)
const corePurchasesIndexRoute = corePurchasesIndexRouteImport.update({
  id: '/purchases/',
  path: '/purchases/',
  getParentRoute: () => coreRouteRoute,
} as any)
const coreMeIndexRoute = coreMeIndexRouteImport.update({
  id: '/me/',
  path: '/me/',
  getParentRoute: () => coreRouteRoute,
} as any)
const coreAdminIndexRoute = coreAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => coreAdminRouteRoute,
} as any)
const ApiSseListsRoute = ApiSseListsRouteImport.update({
  id: '/api/sse/lists',
  path: '/api/sse/lists',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScrapeStreamRoute = ApiScrapeStreamRouteImport.update({
  id: '/api/scrape/stream',
  path: '/api/scrape/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileSplatRoute = ApiMobileSplatRouteImport.update({
  id: '/api/mobile/$',
  path: '/api/mobile/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiListsPublicRoute = ApiListsPublicRouteImport.update({
  id: '/api/lists/public',
  path: '/api/lists/public',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesSplatRoute = ApiFilesSplatRouteImport.update({
  id: '/api/files/$',
  path: '/api/files/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronCleanupVerificationRoute =
  ApiCronCleanupVerificationRouteImport.update({
    id: '/api/cron/cleanup-verification',
    path: '/api/cron/cleanup-verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronBirthdayEmailsRoute = ApiCronBirthdayEmailsRouteImport.update({
  id: '/api/cron/birthday-emails',
  path: '/api/cron/birthday-emails',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronAutoArchiveRoute = ApiCronAutoArchiveRouteImport.update({
  id: '/api/cron/auto-archive',
  path: '/api/cron/auto-archive',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const coreTempWidgetsRoute = coreTempWidgetsRouteImport.update({
  id: '/widgets',
  path: '/widgets',
  getParentRoute: () => coreTempRouteRoute,
} as any)
const coreSettingsSecurityRoute = coreSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => coreSettingsRouteRoute,
} as any)
const coreSettingsPermissionsRoute = coreSettingsPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => coreSettingsRouteRoute,
} as any)
const coreSettingsDevicesRoute = coreSettingsDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => coreSettingsRouteRoute,
} as any)
const coreRecentItemsRoute = coreRecentItemsRouteImport.update({
  id: '/recent/items',
  path: '/recent/items',
  getParentRoute: () => coreRouteRoute,
} as any)
const coreRecentCommentsRoute = coreRecentCommentsRouteImport.update({
  id: '/recent/comments',
  path: '/recent/comments',
  getParentRoute: () => coreRouteRoute,
} as any)
const corePurchasesReceivedRoute = corePurchasesReceivedRouteImport.update({
  id: '/purchases/received',
  path: '/purchases/received',
  getParentRoute: () => coreRouteRoute,
} as any)
const coreOauthConsentRoute = coreOauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => coreRouteRoute,
} as any)
const coreListsListIdRoute = coreListsListIdRouteImport.update({
  id: '/lists/$listId',
  path: '/lists/$listId',
  getParentRoute: () => coreRouteRoute,
} as any)
const coreItemCloneRoute = coreItemCloneRouteImport.update({
  id: '/item/clone',
  path: '/item/clone',
  getParentRoute: () => coreRouteRoute,
} as any)
const coreAdminUsersRoute = coreAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => coreAdminRouteRoute,
} as any)
const coreAdminStorageRoute = coreAdminStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => coreAdminRouteRoute,
} as any)
const coreAdminScrapingRoute = coreAdminScrapingRouteImport.update({
  id: '/scraping',
  path: '/scraping',
  getParentRoute: () => coreAdminRouteRoute,
} as any)
const coreAdminScrapesRoute = coreAdminScrapesRouteImport.update({
  id: '/scrapes',
  path: '/scrapes',
  getParentRoute: () => coreAdminRouteRoute,
} as any)
const coreAdminOidcRoute = coreAdminOidcRouteImport.update({
  id: '/oidc',
  path: '/oidc',
  getParentRoute: () => coreAdminRouteRoute,
} as any)
const coreAdminEmailRoute = coreAdminEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => coreAdminRouteRoute,
} as any)
const coreAdminDebugRoute = coreAdminDebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => coreAdminRouteRoute,
} as any)
const coreAdminDataRoute = coreAdminDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => coreAdminRouteRoute,
} as any)
const coreAdminAiRoute = coreAdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => coreAdminRouteRoute,
} as any)
const authSignInTwoFactorRoute = authSignInTwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => authSignInRoute,
} as any)
const ApiSseListListIdRoute = ApiSseListListIdRouteImport.update({
  id: '/api/sse/list/$listId',
  path: '/api/sse/list/$listId',
  getParentRoute: () => rootRouteImport,
} as any)
const coreListsListIdOrganizeRoute = coreListsListIdOrganizeRouteImport.update({
  id: '/lists_/$listId/organize',
  path: '/lists/$listId/organize',
  getParentRoute: () => coreRouteRoute,
} as any)
const coreListsListIdEditRoute = coreListsListIdEditRouteImport.update({
  id: '/lists_/$listId/edit',
  path: '/lists/$listId/edit',
  getParentRoute: () => coreRouteRoute,
} as any)
const coreListsListIdBulkRoute = coreListsListIdBulkRouteImport.update({
  id: '/lists_/$listId/bulk',
  path: '/lists/$listId/bulk',
  getParentRoute: () => coreRouteRoute,
} as any)
const coreAdminUserIdRoute = coreAdminUserIdRouteImport.update({
  id: '/user/$id',
  path: '/user/$id',
  getParentRoute: () => coreAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof coreAdminRouteRouteWithChildren
  '/settings': typeof coreSettingsRouteRouteWithChildren
  '/temp': typeof coreTempRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRouteWithChildren
  '/sign-out': typeof authSignOutRoute
  '/sign-up': typeof authSignUpRoute
  '/import': typeof coreImportRoute
  '/api/health': typeof ApiHealthRoute
  '/api/version': typeof ApiVersionRoute
  '/': typeof coreIndexRoute
  '/sign-in/two-factor': typeof authSignInTwoFactorRoute
  '/admin/ai': typeof coreAdminAiRoute
  '/admin/data': typeof coreAdminDataRoute
  '/admin/debug': typeof coreAdminDebugRoute
  '/admin/email': typeof coreAdminEmailRoute
  '/admin/oidc': typeof coreAdminOidcRoute
  '/admin/scrapes': typeof coreAdminScrapesRoute
  '/admin/scraping': typeof coreAdminScrapingRoute
  '/admin/storage': typeof coreAdminStorageRoute
  '/admin/users': typeof coreAdminUsersRoute
  '/item/clone': typeof coreItemCloneRoute
  '/lists/$listId': typeof coreListsListIdRoute
  '/oauth/consent': typeof coreOauthConsentRoute
  '/purchases/received': typeof corePurchasesReceivedRoute
  '/recent/comments': typeof coreRecentCommentsRoute
  '/recent/items': typeof coreRecentItemsRoute
  '/settings/devices': typeof coreSettingsDevicesRoute
  '/settings/permissions': typeof coreSettingsPermissionsRoute
  '/settings/security': typeof coreSettingsSecurityRoute
  '/temp/widgets': typeof coreTempWidgetsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/auto-archive': typeof ApiCronAutoArchiveRoute
  '/api/cron/birthday-emails': typeof ApiCronBirthdayEmailsRoute
  '/api/cron/cleanup-verification': typeof ApiCronCleanupVerificationRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/lists/public': typeof ApiListsPublicRoute
  '/api/mobile/$': typeof ApiMobileSplatRoute
  '/api/scrape/stream': typeof ApiScrapeStreamRoute
  '/api/sse/lists': typeof ApiSseListsRoute
  '/admin/': typeof coreAdminIndexRoute
  '/me': typeof coreMeIndexRoute
  '/purchases': typeof corePurchasesIndexRoute
  '/settings/': typeof coreSettingsIndexRoute
  '/temp/': typeof coreTempIndexRoute
  '/admin/user/$id': typeof coreAdminUserIdRoute
  '/lists/$listId/bulk': typeof coreListsListIdBulkRoute
  '/lists/$listId/edit': typeof coreListsListIdEditRoute
  '/lists/$listId/organize': typeof coreListsListIdOrganizeRoute
  '/api/sse/list/$listId': typeof ApiSseListListIdRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRouteWithChildren
  '/sign-out': typeof authSignOutRoute
  '/sign-up': typeof authSignUpRoute
  '/import': typeof coreImportRoute
  '/api/health': typeof ApiHealthRoute
  '/api/version': typeof ApiVersionRoute
  '/': typeof coreIndexRoute
  '/sign-in/two-factor': typeof authSignInTwoFactorRoute
  '/admin/ai': typeof coreAdminAiRoute
  '/admin/data': typeof coreAdminDataRoute
  '/admin/debug': typeof coreAdminDebugRoute
  '/admin/email': typeof coreAdminEmailRoute
  '/admin/oidc': typeof coreAdminOidcRoute
  '/admin/scrapes': typeof coreAdminScrapesRoute
  '/admin/scraping': typeof coreAdminScrapingRoute
  '/admin/storage': typeof coreAdminStorageRoute
  '/admin/users': typeof coreAdminUsersRoute
  '/item/clone': typeof coreItemCloneRoute
  '/lists/$listId': typeof coreListsListIdRoute
  '/oauth/consent': typeof coreOauthConsentRoute
  '/purchases/received': typeof corePurchasesReceivedRoute
  '/recent/comments': typeof coreRecentCommentsRoute
  '/recent/items': typeof coreRecentItemsRoute
  '/settings/devices': typeof coreSettingsDevicesRoute
  '/settings/permissions': typeof coreSettingsPermissionsRoute
  '/settings/security': typeof coreSettingsSecurityRoute
  '/temp/widgets': typeof coreTempWidgetsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/auto-archive': typeof ApiCronAutoArchiveRoute
  '/api/cron/birthday-emails': typeof ApiCronBirthdayEmailsRoute
  '/api/cron/cleanup-verification': typeof ApiCronCleanupVerificationRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/lists/public': typeof ApiListsPublicRoute
  '/api/mobile/$': typeof ApiMobileSplatRoute
  '/api/scrape/stream': typeof ApiScrapeStreamRoute
  '/api/sse/lists': typeof ApiSseListsRoute
  '/admin': typeof coreAdminIndexRoute
  '/me': typeof coreMeIndexRoute
  '/purchases': typeof corePurchasesIndexRoute
  '/settings': typeof coreSettingsIndexRoute
  '/temp': typeof coreTempIndexRoute
  '/admin/user/$id': typeof coreAdminUserIdRoute
  '/lists/$listId/bulk': typeof coreListsListIdBulkRoute
  '/lists/$listId/edit': typeof coreListsListIdEditRoute
  '/lists/$listId/organize': typeof coreListsListIdOrganizeRoute
  '/api/sse/list/$listId': typeof ApiSseListListIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(core)': typeof coreRouteRouteWithChildren
  '/(core)/admin': typeof coreAdminRouteRouteWithChildren
  '/(core)/settings': typeof coreSettingsRouteRouteWithChildren
  '/(core)/temp': typeof coreTempRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRouteWithChildren
  '/(auth)/sign-out': typeof authSignOutRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(core)/import': typeof coreImportRoute
  '/api/health': typeof ApiHealthRoute
  '/api/version': typeof ApiVersionRoute
  '/(core)/': typeof coreIndexRoute
  '/(auth)/sign-in/two-factor': typeof authSignInTwoFactorRoute
  '/(core)/admin/ai': typeof coreAdminAiRoute
  '/(core)/admin/data': typeof coreAdminDataRoute
  '/(core)/admin/debug': typeof coreAdminDebugRoute
  '/(core)/admin/email': typeof coreAdminEmailRoute
  '/(core)/admin/oidc': typeof coreAdminOidcRoute
  '/(core)/admin/scrapes': typeof coreAdminScrapesRoute
  '/(core)/admin/scraping': typeof coreAdminScrapingRoute
  '/(core)/admin/storage': typeof coreAdminStorageRoute
  '/(core)/admin/users': typeof coreAdminUsersRoute
  '/(core)/item/clone': typeof coreItemCloneRoute
  '/(core)/lists/$listId': typeof coreListsListIdRoute
  '/(core)/oauth/consent': typeof coreOauthConsentRoute
  '/(core)/purchases/received': typeof corePurchasesReceivedRoute
  '/(core)/recent/comments': typeof coreRecentCommentsRoute
  '/(core)/recent/items': typeof coreRecentItemsRoute
  '/(core)/settings/devices': typeof coreSettingsDevicesRoute
  '/(core)/settings/permissions': typeof coreSettingsPermissionsRoute
  '/(core)/settings/security': typeof coreSettingsSecurityRoute
  '/(core)/temp/widgets': typeof coreTempWidgetsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/auto-archive': typeof ApiCronAutoArchiveRoute
  '/api/cron/birthday-emails': typeof ApiCronBirthdayEmailsRoute
  '/api/cron/cleanup-verification': typeof ApiCronCleanupVerificationRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/lists/public': typeof ApiListsPublicRoute
  '/api/mobile/$': typeof ApiMobileSplatRoute
  '/api/scrape/stream': typeof ApiScrapeStreamRoute
  '/api/sse/lists': typeof ApiSseListsRoute
  '/(core)/admin/': typeof coreAdminIndexRoute
  '/(core)/me/': typeof coreMeIndexRoute
  '/(core)/purchases/': typeof corePurchasesIndexRoute
  '/(core)/settings/': typeof coreSettingsIndexRoute
  '/(core)/temp/': typeof coreTempIndexRoute
  '/(core)/admin/user/$id': typeof coreAdminUserIdRoute
  '/(core)/lists_/$listId/bulk': typeof coreListsListIdBulkRoute
  '/(core)/lists_/$listId/edit': typeof coreListsListIdEditRoute
  '/(core)/lists_/$listId/organize': typeof coreListsListIdOrganizeRoute
  '/api/sse/list/$listId': typeof ApiSseListListIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/settings'
    | '/temp'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-out'
    | '/sign-up'
    | '/import'
    | '/api/health'
    | '/api/version'
    | '/'
    | '/sign-in/two-factor'
    | '/admin/ai'
    | '/admin/data'
    | '/admin/debug'
    | '/admin/email'
    | '/admin/oidc'
    | '/admin/scrapes'
    | '/admin/scraping'
    | '/admin/storage'
    | '/admin/users'
    | '/item/clone'
    | '/lists/$listId'
    | '/oauth/consent'
    | '/purchases/received'
    | '/recent/comments'
    | '/recent/items'
    | '/settings/devices'
    | '/settings/permissions'
    | '/settings/security'
    | '/temp/widgets'
    | '/api/auth/$'
    | '/api/cron/auto-archive'
    | '/api/cron/birthday-emails'
    | '/api/cron/cleanup-verification'
    | '/api/files/$'
    | '/api/lists/public'
    | '/api/mobile/$'
    | '/api/scrape/stream'
    | '/api/sse/lists'
    | '/admin/'
    | '/me'
    | '/purchases'
    | '/settings/'
    | '/temp/'
    | '/admin/user/$id'
    | '/lists/$listId/bulk'
    | '/lists/$listId/edit'
    | '/lists/$listId/organize'
    | '/api/sse/list/$listId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-out'
    | '/sign-up'
    | '/import'
    | '/api/health'
    | '/api/version'
    | '/'
    | '/sign-in/two-factor'
    | '/admin/ai'
    | '/admin/data'
    | '/admin/debug'
    | '/admin/email'
    | '/admin/oidc'
    | '/admin/scrapes'
    | '/admin/scraping'
    | '/admin/storage'
    | '/admin/users'
    | '/item/clone'
    | '/lists/$listId'
    | '/oauth/consent'
    | '/purchases/received'
    | '/recent/comments'
    | '/recent/items'
    | '/settings/devices'
    | '/settings/permissions'
    | '/settings/security'
    | '/temp/widgets'
    | '/api/auth/$'
    | '/api/cron/auto-archive'
    | '/api/cron/birthday-emails'
    | '/api/cron/cleanup-verification'
    | '/api/files/$'
    | '/api/lists/public'
    | '/api/mobile/$'
    | '/api/scrape/stream'
    | '/api/sse/lists'
    | '/admin'
    | '/me'
    | '/purchases'
    | '/settings'
    | '/temp'
    | '/admin/user/$id'
    | '/lists/$listId/bulk'
    | '/lists/$listId/edit'
    | '/lists/$listId/organize'
    | '/api/sse/list/$listId'
  id:
    | '__root__'
    | '/(core)'
    | '/(core)/admin'
    | '/(core)/settings'
    | '/(core)/temp'
    | '/(auth)/forgot-password'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-out'
    | '/(auth)/sign-up'
    | '/(core)/import'
    | '/api/health'
    | '/api/version'
    | '/(core)/'
    | '/(auth)/sign-in/two-factor'
    | '/(core)/admin/ai'
    | '/(core)/admin/data'
    | '/(core)/admin/debug'
    | '/(core)/admin/email'
    | '/(core)/admin/oidc'
    | '/(core)/admin/scrapes'
    | '/(core)/admin/scraping'
    | '/(core)/admin/storage'
    | '/(core)/admin/users'
    | '/(core)/item/clone'
    | '/(core)/lists/$listId'
    | '/(core)/oauth/consent'
    | '/(core)/purchases/received'
    | '/(core)/recent/comments'
    | '/(core)/recent/items'
    | '/(core)/settings/devices'
    | '/(core)/settings/permissions'
    | '/(core)/settings/security'
    | '/(core)/temp/widgets'
    | '/api/auth/$'
    | '/api/cron/auto-archive'
    | '/api/cron/birthday-emails'
    | '/api/cron/cleanup-verification'
    | '/api/files/$'
    | '/api/lists/public'
    | '/api/mobile/$'
    | '/api/scrape/stream'
    | '/api/sse/lists'
    | '/(core)/admin/'
    | '/(core)/me/'
    | '/(core)/purchases/'
    | '/(core)/settings/'
    | '/(core)/temp/'
    | '/(core)/admin/user/$id'
    | '/(core)/lists_/$listId/bulk'
    | '/(core)/lists_/$listId/edit'
    | '/(core)/lists_/$listId/organize'
    | '/api/sse/list/$listId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  coreRouteRoute: typeof coreRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRouteWithChildren
  authSignOutRoute: typeof authSignOutRoute
  authSignUpRoute: typeof authSignUpRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiVersionRoute: typeof ApiVersionRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronAutoArchiveRoute: typeof ApiCronAutoArchiveRoute
  ApiCronBirthdayEmailsRoute: typeof ApiCronBirthdayEmailsRoute
  ApiCronCleanupVerificationRoute: typeof ApiCronCleanupVerificationRoute
  ApiFilesSplatRoute: typeof ApiFilesSplatRoute
  ApiListsPublicRoute: typeof ApiListsPublicRoute
  ApiMobileSplatRoute: typeof ApiMobileSplatRoute
  ApiScrapeStreamRoute: typeof ApiScrapeStreamRoute
  ApiSseListsRoute: typeof ApiSseListsRoute
  ApiSseListListIdRoute: typeof ApiSseListListIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(core)': {
      id: '/(core)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof coreRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(core)/': {
      id: '/(core)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof coreIndexRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/api/version': {
      id: '/api/version'
      path: '/api/version'
      fullPath: '/api/version'
      preLoaderRoute: typeof ApiVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(core)/import': {
      id: '/(core)/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof coreImportRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-out': {
      id: '/(auth)/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof authSignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(core)/temp': {
      id: '/(core)/temp'
      path: '/temp'
      fullPath: '/temp'
      preLoaderRoute: typeof coreTempRouteRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/(core)/settings': {
      id: '/(core)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof coreSettingsRouteRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/(core)/admin': {
      id: '/(core)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof coreAdminRouteRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/(core)/temp/': {
      id: '/(core)/temp/'
      path: '/'
      fullPath: '/temp/'
      preLoaderRoute: typeof coreTempIndexRouteImport
      parentRoute: typeof coreTempRouteRoute
    }
    '/(core)/settings/': {
      id: '/(core)/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof coreSettingsIndexRouteImport
      parentRoute: typeof coreSettingsRouteRoute
    }
    '/(core)/purchases/': {
      id: '/(core)/purchases/'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof corePurchasesIndexRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/(core)/me/': {
      id: '/(core)/me/'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof coreMeIndexRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/(core)/admin/': {
      id: '/(core)/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof coreAdminIndexRouteImport
      parentRoute: typeof coreAdminRouteRoute
    }
    '/api/sse/lists': {
      id: '/api/sse/lists'
      path: '/api/sse/lists'
      fullPath: '/api/sse/lists'
      preLoaderRoute: typeof ApiSseListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scrape/stream': {
      id: '/api/scrape/stream'
      path: '/api/scrape/stream'
      fullPath: '/api/scrape/stream'
      preLoaderRoute: typeof ApiScrapeStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/$': {
      id: '/api/mobile/$'
      path: '/api/mobile/$'
      fullPath: '/api/mobile/$'
      preLoaderRoute: typeof ApiMobileSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lists/public': {
      id: '/api/lists/public'
      path: '/api/lists/public'
      fullPath: '/api/lists/public'
      preLoaderRoute: typeof ApiListsPublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$': {
      id: '/api/files/$'
      path: '/api/files/$'
      fullPath: '/api/files/$'
      preLoaderRoute: typeof ApiFilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/cleanup-verification': {
      id: '/api/cron/cleanup-verification'
      path: '/api/cron/cleanup-verification'
      fullPath: '/api/cron/cleanup-verification'
      preLoaderRoute: typeof ApiCronCleanupVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/birthday-emails': {
      id: '/api/cron/birthday-emails'
      path: '/api/cron/birthday-emails'
      fullPath: '/api/cron/birthday-emails'
      preLoaderRoute: typeof ApiCronBirthdayEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/auto-archive': {
      id: '/api/cron/auto-archive'
      path: '/api/cron/auto-archive'
      fullPath: '/api/cron/auto-archive'
      preLoaderRoute: typeof ApiCronAutoArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(core)/temp/widgets': {
      id: '/(core)/temp/widgets'
      path: '/widgets'
      fullPath: '/temp/widgets'
      preLoaderRoute: typeof coreTempWidgetsRouteImport
      parentRoute: typeof coreTempRouteRoute
    }
    '/(core)/settings/security': {
      id: '/(core)/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof coreSettingsSecurityRouteImport
      parentRoute: typeof coreSettingsRouteRoute
    }
    '/(core)/settings/permissions': {
      id: '/(core)/settings/permissions'
      path: '/permissions'
      fullPath: '/settings/permissions'
      preLoaderRoute: typeof coreSettingsPermissionsRouteImport
      parentRoute: typeof coreSettingsRouteRoute
    }
    '/(core)/settings/devices': {
      id: '/(core)/settings/devices'
      path: '/devices'
      fullPath: '/settings/devices'
      preLoaderRoute: typeof coreSettingsDevicesRouteImport
      parentRoute: typeof coreSettingsRouteRoute
    }
    '/(core)/recent/items': {
      id: '/(core)/recent/items'
      path: '/recent/items'
      fullPath: '/recent/items'
      preLoaderRoute: typeof coreRecentItemsRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/(core)/recent/comments': {
      id: '/(core)/recent/comments'
      path: '/recent/comments'
      fullPath: '/recent/comments'
      preLoaderRoute: typeof coreRecentCommentsRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/(core)/purchases/received': {
      id: '/(core)/purchases/received'
      path: '/purchases/received'
      fullPath: '/purchases/received'
      preLoaderRoute: typeof corePurchasesReceivedRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/(core)/oauth/consent': {
      id: '/(core)/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof coreOauthConsentRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/(core)/lists/$listId': {
      id: '/(core)/lists/$listId'
      path: '/lists/$listId'
      fullPath: '/lists/$listId'
      preLoaderRoute: typeof coreListsListIdRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/(core)/item/clone': {
      id: '/(core)/item/clone'
      path: '/item/clone'
      fullPath: '/item/clone'
      preLoaderRoute: typeof coreItemCloneRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/(core)/admin/users': {
      id: '/(core)/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof coreAdminUsersRouteImport
      parentRoute: typeof coreAdminRouteRoute
    }
    '/(core)/admin/storage': {
      id: '/(core)/admin/storage'
      path: '/storage'
      fullPath: '/admin/storage'
      preLoaderRoute: typeof coreAdminStorageRouteImport
      parentRoute: typeof coreAdminRouteRoute
    }
    '/(core)/admin/scraping': {
      id: '/(core)/admin/scraping'
      path: '/scraping'
      fullPath: '/admin/scraping'
      preLoaderRoute: typeof coreAdminScrapingRouteImport
      parentRoute: typeof coreAdminRouteRoute
    }
    '/(core)/admin/scrapes': {
      id: '/(core)/admin/scrapes'
      path: '/scrapes'
      fullPath: '/admin/scrapes'
      preLoaderRoute: typeof coreAdminScrapesRouteImport
      parentRoute: typeof coreAdminRouteRoute
    }
    '/(core)/admin/oidc': {
      id: '/(core)/admin/oidc'
      path: '/oidc'
      fullPath: '/admin/oidc'
      preLoaderRoute: typeof coreAdminOidcRouteImport
      parentRoute: typeof coreAdminRouteRoute
    }
    '/(core)/admin/email': {
      id: '/(core)/admin/email'
      path: '/email'
      fullPath: '/admin/email'
      preLoaderRoute: typeof coreAdminEmailRouteImport
      parentRoute: typeof coreAdminRouteRoute
    }
    '/(core)/admin/debug': {
      id: '/(core)/admin/debug'
      path: '/debug'
      fullPath: '/admin/debug'
      preLoaderRoute: typeof coreAdminDebugRouteImport
      parentRoute: typeof coreAdminRouteRoute
    }
    '/(core)/admin/data': {
      id: '/(core)/admin/data'
      path: '/data'
      fullPath: '/admin/data'
      preLoaderRoute: typeof coreAdminDataRouteImport
      parentRoute: typeof coreAdminRouteRoute
    }
    '/(core)/admin/ai': {
      id: '/(core)/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof coreAdminAiRouteImport
      parentRoute: typeof coreAdminRouteRoute
    }
    '/(auth)/sign-in/two-factor': {
      id: '/(auth)/sign-in/two-factor'
      path: '/two-factor'
      fullPath: '/sign-in/two-factor'
      preLoaderRoute: typeof authSignInTwoFactorRouteImport
      parentRoute: typeof authSignInRoute
    }
    '/api/sse/list/$listId': {
      id: '/api/sse/list/$listId'
      path: '/api/sse/list/$listId'
      fullPath: '/api/sse/list/$listId'
      preLoaderRoute: typeof ApiSseListListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(core)/lists_/$listId/organize': {
      id: '/(core)/lists_/$listId/organize'
      path: '/lists/$listId/organize'
      fullPath: '/lists/$listId/organize'
      preLoaderRoute: typeof coreListsListIdOrganizeRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/(core)/lists_/$listId/edit': {
      id: '/(core)/lists_/$listId/edit'
      path: '/lists/$listId/edit'
      fullPath: '/lists/$listId/edit'
      preLoaderRoute: typeof coreListsListIdEditRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/(core)/lists_/$listId/bulk': {
      id: '/(core)/lists_/$listId/bulk'
      path: '/lists/$listId/bulk'
      fullPath: '/lists/$listId/bulk'
      preLoaderRoute: typeof coreListsListIdBulkRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/(core)/admin/user/$id': {
      id: '/(core)/admin/user/$id'
      path: '/user/$id'
      fullPath: '/admin/user/$id'
      preLoaderRoute: typeof coreAdminUserIdRouteImport
      parentRoute: typeof coreAdminRouteRoute
    }
  }
}

interface coreAdminRouteRouteChildren {
  coreAdminAiRoute: typeof coreAdminAiRoute
  coreAdminDataRoute: typeof coreAdminDataRoute
  coreAdminDebugRoute: typeof coreAdminDebugRoute
  coreAdminEmailRoute: typeof coreAdminEmailRoute
  coreAdminOidcRoute: typeof coreAdminOidcRoute
  coreAdminScrapesRoute: typeof coreAdminScrapesRoute
  coreAdminScrapingRoute: typeof coreAdminScrapingRoute
  coreAdminStorageRoute: typeof coreAdminStorageRoute
  coreAdminUsersRoute: typeof coreAdminUsersRoute
  coreAdminIndexRoute: typeof coreAdminIndexRoute
  coreAdminUserIdRoute: typeof coreAdminUserIdRoute
}

const coreAdminRouteRouteChildren: coreAdminRouteRouteChildren = {
  coreAdminAiRoute: coreAdminAiRoute,
  coreAdminDataRoute: coreAdminDataRoute,
  coreAdminDebugRoute: coreAdminDebugRoute,
  coreAdminEmailRoute: coreAdminEmailRoute,
  coreAdminOidcRoute: coreAdminOidcRoute,
  coreAdminScrapesRoute: coreAdminScrapesRoute,
  coreAdminScrapingRoute: coreAdminScrapingRoute,
  coreAdminStorageRoute: coreAdminStorageRoute,
  coreAdminUsersRoute: coreAdminUsersRoute,
  coreAdminIndexRoute: coreAdminIndexRoute,
  coreAdminUserIdRoute: coreAdminUserIdRoute,
}

const coreAdminRouteRouteWithChildren = coreAdminRouteRoute._addFileChildren(
  coreAdminRouteRouteChildren,
)

interface coreSettingsRouteRouteChildren {
  coreSettingsDevicesRoute: typeof coreSettingsDevicesRoute
  coreSettingsPermissionsRoute: typeof coreSettingsPermissionsRoute
  coreSettingsSecurityRoute: typeof coreSettingsSecurityRoute
  coreSettingsIndexRoute: typeof coreSettingsIndexRoute
}

const coreSettingsRouteRouteChildren: coreSettingsRouteRouteChildren = {
  coreSettingsDevicesRoute: coreSettingsDevicesRoute,
  coreSettingsPermissionsRoute: coreSettingsPermissionsRoute,
  coreSettingsSecurityRoute: coreSettingsSecurityRoute,
  coreSettingsIndexRoute: coreSettingsIndexRoute,
}

const coreSettingsRouteRouteWithChildren =
  coreSettingsRouteRoute._addFileChildren(coreSettingsRouteRouteChildren)

interface coreTempRouteRouteChildren {
  coreTempWidgetsRoute: typeof coreTempWidgetsRoute
  coreTempIndexRoute: typeof coreTempIndexRoute
}

const coreTempRouteRouteChildren: coreTempRouteRouteChildren = {
  coreTempWidgetsRoute: coreTempWidgetsRoute,
  coreTempIndexRoute: coreTempIndexRoute,
}

const coreTempRouteRouteWithChildren = coreTempRouteRoute._addFileChildren(
  coreTempRouteRouteChildren,
)

interface coreRouteRouteChildren {
  coreAdminRouteRoute: typeof coreAdminRouteRouteWithChildren
  coreSettingsRouteRoute: typeof coreSettingsRouteRouteWithChildren
  coreTempRouteRoute: typeof coreTempRouteRouteWithChildren
  coreImportRoute: typeof coreImportRoute
  coreIndexRoute: typeof coreIndexRoute
  coreItemCloneRoute: typeof coreItemCloneRoute
  coreListsListIdRoute: typeof coreListsListIdRoute
  coreOauthConsentRoute: typeof coreOauthConsentRoute
  corePurchasesReceivedRoute: typeof corePurchasesReceivedRoute
  coreRecentCommentsRoute: typeof coreRecentCommentsRoute
  coreRecentItemsRoute: typeof coreRecentItemsRoute
  coreMeIndexRoute: typeof coreMeIndexRoute
  corePurchasesIndexRoute: typeof corePurchasesIndexRoute
  coreListsListIdBulkRoute: typeof coreListsListIdBulkRoute
  coreListsListIdEditRoute: typeof coreListsListIdEditRoute
  coreListsListIdOrganizeRoute: typeof coreListsListIdOrganizeRoute
}

const coreRouteRouteChildren: coreRouteRouteChildren = {
  coreAdminRouteRoute: coreAdminRouteRouteWithChildren,
  coreSettingsRouteRoute: coreSettingsRouteRouteWithChildren,
  coreTempRouteRoute: coreTempRouteRouteWithChildren,
  coreImportRoute: coreImportRoute,
  coreIndexRoute: coreIndexRoute,
  coreItemCloneRoute: coreItemCloneRoute,
  coreListsListIdRoute: coreListsListIdRoute,
  coreOauthConsentRoute: coreOauthConsentRoute,
  corePurchasesReceivedRoute: corePurchasesReceivedRoute,
  coreRecentCommentsRoute: coreRecentCommentsRoute,
  coreRecentItemsRoute: coreRecentItemsRoute,
  coreMeIndexRoute: coreMeIndexRoute,
  corePurchasesIndexRoute: corePurchasesIndexRoute,
  coreListsListIdBulkRoute: coreListsListIdBulkRoute,
  coreListsListIdEditRoute: coreListsListIdEditRoute,
  coreListsListIdOrganizeRoute: coreListsListIdOrganizeRoute,
}

const coreRouteRouteWithChildren = coreRouteRoute._addFileChildren(
  coreRouteRouteChildren,
)

interface authSignInRouteChildren {
  authSignInTwoFactorRoute: typeof authSignInTwoFactorRoute
}

const authSignInRouteChildren: authSignInRouteChildren = {
  authSignInTwoFactorRoute: authSignInTwoFactorRoute,
}

const authSignInRouteWithChildren = authSignInRoute._addFileChildren(
  authSignInRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  coreRouteRoute: coreRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRouteWithChildren,
  authSignOutRoute: authSignOutRoute,
  authSignUpRoute: authSignUpRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiVersionRoute: ApiVersionRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronAutoArchiveRoute: ApiCronAutoArchiveRoute,
  ApiCronBirthdayEmailsRoute: ApiCronBirthdayEmailsRoute,
  ApiCronCleanupVerificationRoute: ApiCronCleanupVerificationRoute,
  ApiFilesSplatRoute: ApiFilesSplatRoute,
  ApiListsPublicRoute: ApiListsPublicRoute,
  ApiMobileSplatRoute: ApiMobileSplatRoute,
  ApiScrapeStreamRoute: ApiScrapeStreamRoute,
  ApiSseListsRoute: ApiSseListsRoute,
  ApiSseListListIdRoute: ApiSseListListIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
